language: go

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6

go:
  - "1.10.x"

before_install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90

script:
  - make test-coverage codecov

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: make test-coverage codecov
    - script: make test-sdk
      name: "Integration Tests"
    - script:
        - make protogen
        - make no-changes-in-commit
      name: "Protobuf code generation"

cache:
  directories:
    - $HOME/protoc
